import mongoose from 'mongoose';

export const doctorSchema = new mongoose.Schema({
    bookedTimesId: Number,
    clinicId: [Number],
    certificates: String,
    clinicSchedule: [Number],
    education: String,
    id: { type: Number, unique: true },
    largePhoto: String,
    name: String,
    professionalInterests: String,
    price: Number,
    specialtyId: [Number],
    smallPhoto: String,
    timeSchedule: [String],
    worksWithVhi: Boolean,
    worksWithKids: Boolean,
    worksOnline: Boolean,
});

export const Doctor = mongoose.model('Doctor', doctorSchema);

export const doctors = [
    {
        bookedTimesId: 1,
        clinicId: [2],
        certificates: 'American Board of Internal Medicine, American Board of Pediatrics',
        clinicSchedule: [2, 2, 2, 2, 2],
        education: 'Graduated from Harvard Medical School',
        id: 1,
        largePhoto: 'https://i.imgur.com/svDvHca.png',
        name: 'Alice Johnson',
        professionalInterests: 'Preventive medicine, chronic disease management',
        price: 175,
        specialtyId: [1, 14],
        smallPhoto: 'https://i.imgur.com/STIwo0S.png',
        timeSchedule: ['11:00', '12:00', '14:00', '18:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: true,
    },
    {
        bookedTimesId: 2,
        clinicId: [1, 2],
        certificates:
            'American Board of Family Medicine, American Board of Preventive Medicine',
        clinicSchedule: [1, 2, 1, 2, 1],
        education: 'Graduated from Stanford School of Medicine',
        id: 2,
        largePhoto: 'https://i.imgur.com/Lvlrf4w.png',
        name: 'John Smith',
        professionalInterests: 'Primary care, health promotion and disease prevention',
        price: 125,
        specialtyId: [2, 13],
        smallPhoto: 'https://i.imgur.com/F3gN81X.png',
        timeSchedule: ['12:00', '15:00', '17:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 3,
        clinicId: [2, 3],
        certificates: 'American Board of Obstetrics and Gynecology',
        clinicSchedule: [2, 2, 3, 2, 3],
        education: 'Graduated from Yale School of Medicine',
        id: 3,
        largePhoto: 'https://i.imgur.com/V33QqVK.png',
        name: 'Emma Brown',
        professionalInterests: "Women's health, reproductive health, family planning",
        price: 225,
        specialtyId: [11, 16],
        smallPhoto: 'https://i.imgur.com/P4sogcR.png',
        timeSchedule: ['10:00', '11:00', '12:00', '14:00', '17:00', '18:00', '19:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: true,
    },
    {
        bookedTimesId: 4,
        clinicId: [1, 2],
        certificates: 'American Board of Dermatology, American Board of Pediatrics',
        clinicSchedule: [2, 1, 1, 1, 2],
        education:
            'Graduated from University of California, San Francisco School of Medicine',
        id: 4,
        largePhoto: 'https://i.imgur.com/qgAoQrc.png',
        name: 'Michael Lee',
        professionalInterests:
            'Skin cancer prevention and treatment, pediatric dermatology',
        price: 175,
        specialtyId: [1, 4],
        smallPhoto: 'https://i.imgur.com/93MJnaw.png',
        timeSchedule: ['09:00', '11:00', '15:00', '17:00', '18:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: false,
    },
    {
        bookedTimesId: 5,
        clinicId: [1],
        certificates: 'American Board of Ophthalmology',
        clinicSchedule: [1, 1, 1, 1, 1],
        education:
            'Graduated from University of Pennsylvania, Perelman School of Medicine',
        id: 5,
        largePhoto: 'https://i.imgur.com/8Zqja1a.png',
        name: 'Jennifer Chen',
        professionalInterests: 'Pediatric ophthalmology, strabismus, amblyopia',
        price: 175,
        specialtyId: [5],
        smallPhoto: 'https://i.imgur.com/dfsL0lw.png',
        timeSchedule: ['09:00', '10:00', '16:00', '18:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: true,
    },
    {
        bookedTimesId: 6,
        clinicId: [1],
        certificates:
            'American Board of Neurology, American Board of Psychiatry and Neurology',
        clinicSchedule: [1, 1, 1, 1, 1],
        education:
            'Graduated from Columbia University, Vagelos College of Physicians and Surgeons',
        id: 6,
        largePhoto: 'https://i.imgur.com/egA2DqI.png',
        name: 'David Kim',
        professionalInterests:
            'Child and adolescent psychiatry, neurodevelopmental disorders',
        price: 150,
        specialtyId: [3, 7],
        smallPhoto: 'https://i.imgur.com/HP84T6p.png',
        timeSchedule: ['09:00', '12:00', '13:00', '16:00', '17:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 7,
        clinicId: [3, 4],
        certificates:
            'American Board of Pediatrics, American Board of Allergy and Immunology',
        clinicSchedule: [3, 3, 4, 3, 4],
        education: 'Graduated from University of Michigan Medical School',
        id: 7,
        largePhoto: 'https://i.imgur.com/kll6qQv.png',
        name: 'Sarah Davis',
        professionalInterests: 'Pediatric allergy and immunology, food allergy, asthma',
        price: 125,
        specialtyId: [1, 6],
        smallPhoto: 'https://i.imgur.com/th1Xjxa.png',
        timeSchedule: ['10:00', '11:00', '12:00', '13:00', '16:00', '18:00'],
        worksWithVhi: true,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 8,
        clinicId: [2, 4],
        certificates:
            'American Board of Pediatrics, American Board of Pediatric Cardiology',
        clinicSchedule: [2, 2, 2, 4, 2],
        education: 'Graduated from University of Texas, Southwestern Medical School',
        id: 8,
        largePhoto: 'https://i.imgur.com/y78VvWs.png',
        name: 'Robert Wilson',
        professionalInterests: 'Pediatric cardiology, congenital heart disease',
        price: 175,
        specialtyId: [1, 8],
        smallPhoto: 'https://i.imgur.com/PNONz67.png',
        timeSchedule: [
            '09:00',
            '10:00',
            '14:00',
            '15:00',
            '16:00',
            '17:00',
            '18:00',
            '19:00',
        ],
        worksWithVhi: true,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 9,
        clinicId: [4],
        certificates: 'American Board of Pediatrics',
        clinicSchedule: [4, 4, 4, 4, 4],
        education:
            'Graduated from University of California, Los Angeles David Geffen School of Medicine',
        id: 9,
        largePhoto: 'https://i.imgur.com/IojOqLO.png',
        name: 'Laura Martinez',
        professionalInterests: 'Pediatric emergency medicine, trauma',
        price: 225,
        specialtyId: [9, 1],
        smallPhoto: 'https://i.imgur.com/HmvZbJF.png',
        timeSchedule: ['10:00', '12:00', '15:00', '16:00', '17:00', '18:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 10,
        clinicId: [2, 3],
        certificates:
            'American Board of Internal Medicine, American Board of Gastroenterology',
        clinicSchedule: [3, 2, 2, 2, 3],
        education: 'Graduated from University of Chicago, Pritzker School of Medicine',
        id: 10,
        largePhoto: 'https://i.imgur.com/HUGuinN.png',
        name: 'William Yang',
        professionalInterests: 'Gastroenterology, inflammatory bowel disease, nutrition',
        price: 150,
        specialtyId: [10, 14],
        smallPhoto: 'https://i.imgur.com/iNlo7EE.png',
        timeSchedule: ['09:00', '13:00', '15:00', '16:00', '17:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: false,
    },
    {
        bookedTimesId: 11,
        clinicId: [2, 4],
        certificates:
            'American Board of Pediatrics, American Board of Pediatric Hematology/Oncology',
        clinicSchedule: [2, 4, 4, 2, 4],
        education: 'Graduated from University of Washington School of Medicine',
        id: 11,
        largePhoto: 'https://i.imgur.com/H6J7cgm.png',
        name: 'Olivia Kim',
        professionalInterests: 'Pediatric hematology/oncology, leukemia, lymphoma',
        price: 150,
        specialtyId: [9, 11],
        smallPhoto: 'https://i.imgur.com/r1bBgVB.png',
        timeSchedule: ['09:00', '10:00', '14:00', '16:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 12,
        clinicId: [1, 3],
        certificates: 'American Board of Surgery, American Board of Plastic Surgery',
        clinicSchedule: [3, 1, 1, 3, 1],
        education:
            'Graduated from University of California, San Diego School of Medicine',
        id: 12,
        largePhoto: 'https://i.imgur.com/EHFRPMd.png',
        name: 'Andrew Park',
        professionalInterests:
            'Plastic and reconstructive surgery, breast reconstruction, hand surgery',
        price: 225,
        specialtyId: [4, 12],
        smallPhoto: 'https://i.imgur.com/NWZkt0M.png',
        timeSchedule: ['09:00', '12:00', '13:00', '16:00', '17:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: true,
    },
    {
        bookedTimesId: 13,
        clinicId: [2, 4],
        certificates: 'American Board of Pediatrics, American Board of Cardiology',
        clinicSchedule: [1, 1, 2, 2, 3],
        education: 'Graduated from Harvard Medical School',
        id: 13,
        largePhoto: 'https://i.imgur.com/iz40qYn.png',
        name: 'Emily Johnson',
        professionalInterests: 'Pediatrics, cardiology',
        price: 225,
        specialtyId: [1, 2],
        smallPhoto: 'https://i.imgur.com/5gdVfpA.png',
        timeSchedule: ['10:00', '13:00', '14:00', '17:00', '18:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: true,
    },
    {
        bookedTimesId: 14,
        clinicId: [1, 2, 3],
        certificates: 'American Board of Neurology, American Board of Dermatology',
        clinicSchedule: [2, 2, 3, 4, 4],
        education: 'Graduated from Johns Hopkins School of Medicine',
        id: 14,
        largePhoto: 'https://i.imgur.com/VzI7I9v.png',
        name: 'Emily Park',
        professionalInterests: 'Neurology, dermatology',
        price: 225,
        specialtyId: [3, 4],
        smallPhoto: 'https://i.imgur.com/1TmB6CJ.png',
        timeSchedule: ['11:00', '14:00', '15:00', '18:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: false,
    },
    {
        bookedTimesId: 15,
        clinicId: [1, 3, 4],
        certificates:
            'American Board of Ophthalmology, American Board of Allergy and Immunology',
        clinicSchedule: [1, 3, 4, 4, 2],
        education: 'Graduated from Stanford University School of Medicine',
        id: 15,
        largePhoto: 'https://i.imgur.com/MPi89Za.png',
        name: 'David Miller',
        professionalInterests: 'Ophthalmology, allergy and immunology',
        price: 225,
        specialtyId: [5, 6],
        smallPhoto: 'https://i.imgur.com/4WOHsGb.png',
        timeSchedule: ['09:00', '12:00', '13:00', '16:00', '17:00'],
        worksWithVhi: true,
        worksWithKids: true,
        worksOnline: true,
    },
    {
        bookedTimesId: 16,
        clinicId: [2, 3, 4],
        certificates:
            'Board Certified in Gastroenterology, American Board of Internal Medicine',
        clinicSchedule: [3, 4, 1, 2, 3],
        education: 'Graduated from University of Pennsylvania School of Medicine',
        id: 16,
        largePhoto: 'https://i.imgur.com/qFf4gwL.png',
        name: 'Michael Anderson',
        professionalInterests: 'Internal medicine, gastroenterology',
        price: 225,
        specialtyId: [14, 10],
        smallPhoto: 'https://i.imgur.com/1zDTDUy.png',
        timeSchedule: ['10:00', '13:00', '14:00', '17:00', '18:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: true,
    },
    {
        bookedTimesId: 17,
        clinicId: [1, 2, 4],
        certificates:
            'Fellowship Trained in Pediatric Hematology/Oncology, American Board of Plastic Surgery',
        clinicSchedule: [2, 3, 4, 1, 2],
        education: 'Graduated from Harvard Medical School',
        id: 17,
        largePhoto: 'https://i.imgur.com/Wy6YQMi.png',
        name: 'Elizabeth Taylor',
        professionalInterests: 'Pediatric hematology/oncology, plastic surgery',
        price: 225,
        specialtyId: [11, 12],
        smallPhoto: 'https://i.imgur.com/7HYeqiC.png',
        timeSchedule: ['11:00', '14:00', '15:00', '18:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: false,
    },
    {
        bookedTimesId: 18,
        clinicId: [1, 3, 4],
        certificates:
            'American Board of Psychiatry, American Board of Pediatric Cardiology',
        clinicSchedule: [4, 1, 2, 2, 3],
        education: 'Graduated from Yale School of Medicine',
        id: 18,
        largePhoto: 'https://i.imgur.com/hRFvxzz.png',
        name: 'Andrew Wilson',
        professionalInterests: 'Psychiatry, pediatric cardiology',
        price: 225,
        specialtyId: [7, 8],
        smallPhoto: 'https://i.imgur.com/VvDlvlU.png',
        timeSchedule: ['11:00', '14:00', '15:00', '18:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 19,
        clinicId: [2, 3, 4],
        certificates:
            'American Board of Family Medicine, American Board of Internal Medicine',
        clinicSchedule: [1, 2, 3, 4, 1],
        education: 'Graduated from University of Michigan Medical School',
        id: 19,
        largePhoto: 'https://i.imgur.com/5uxymAU.png',
        name: 'Samantha Brown',
        professionalInterests: 'Family medicine, internal medicine',
        price: 225,
        specialtyId: [13, 14],
        smallPhoto: 'https://i.imgur.com/rnyT5cU.png',
        timeSchedule: ['10:00', '13:00', '14:00', '17:00', '18:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: true,
    },
    {
        bookedTimesId: 20,
        clinicId: [1, 2, 3],
        certificates: 'American Board of Oncology, American Board of Gynecology',
        clinicSchedule: [3, 4, 1, 1, 2],
        education:
            'Graduated from Columbia University Vagelos College of Physicians and Surgeons',
        id: 20,
        largePhoto: 'https://i.imgur.com/u9LgkXp.png',
        name: 'Emily Thompson',
        professionalInterests: 'Oncology, gynecology',
        price: 225,
        specialtyId: [15, 16],
        smallPhoto: 'https://i.imgur.com/IMXoQLT.png',
        timeSchedule: ['09:00', '12:00', '13:00', '16:00', '17:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: true,
    },
    {
        bookedTimesId: 21,
        clinicId: [1, 2, 3],
        certificates: 'American Board of Gynecology, American Board of Andrology',
        clinicSchedule: [1, 2, 3, 4, 1],
        education: 'Graduated from University of Chicago Pritzker School of Medicine',
        id: 21,
        largePhoto: 'https://i.imgur.com/ZOxMoel.png',
        name: 'Christopher Clark',
        professionalInterests: 'Andrology, pediatrics',
        price: 225,
        specialtyId: [16, 17],
        smallPhoto: 'https://i.imgur.com/hlFuidJ.png',
        timeSchedule: ['10:00', '13:00', '14:00', '17:00', '18:00'],
        worksWithVhi: true,
        worksWithKids: true,
        worksOnline: false,
    },
    {
        bookedTimesId: 22,
        clinicId: [2, 3, 4],
        certificates: 'American Board of Cardiology, American Board of Plastic Surgery',
        clinicSchedule: [2, 3, 4, 1, 2],
        education: 'Graduated from Stanford University School of Medicine',
        id: 22,
        largePhoto: 'https://i.imgur.com/X9MGffx.png',
        name: 'Jessica Wilson',
        professionalInterests: 'Cardiology, plastic surgery',
        price: 225,
        specialtyId: [2, 12],
        smallPhoto: 'https://i.imgur.com/C7jvWCb.png',
        timeSchedule: ['11:00', '14:00', '15:00', '18:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: true,
    },
    {
        bookedTimesId: 23,
        clinicId: [1, 3, 4],
        certificates:
            'American Board of Dermatology, American Board of Emergency Medicine',
        clinicSchedule: [4, 1, 2, 3, 4],
        education:
            'Graduated from University of California, San Francisco School of Medicine',
        id: 23,
        largePhoto: 'https://i.imgur.com/xyL2udv.png',
        name: 'Megan Adams',
        professionalInterests: 'Dermatology, emergency medicine',
        price: 225,
        specialtyId: [4, 9],
        smallPhoto: 'https://i.imgur.com/YpyJiMV.png',
        timeSchedule: ['11:00', '14:00', '15:00', '18:00', '19:00'],
        worksWithVhi: true,
        worksWithKids: false,
        worksOnline: true,
    },
    {
        bookedTimesId: 24,
        clinicId: [1, 2, 4],
        certificates:
            'American Board of Neurology, American Board of Allergy and Immunology',
        clinicSchedule: [2, 3, 4, 1, 2],
        education: 'Graduated from Johns Hopkins University School of Medicine',
        id: 24,
        largePhoto: 'https://i.imgur.com/uJnoVzg.png',
        name: 'Robert Harris',
        professionalInterests: 'Neurology, allergy and immunology',
        price: 225,
        specialtyId: [3, 6],
        smallPhoto: 'https://i.imgur.com/UoSn2yi.png',
        timeSchedule: ['10:00', '13:00', '14:00', '17:00', '18:00'],
        worksWithVhi: false,
        worksWithKids: true,
        worksOnline: true,
    },
];
